# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
# using https://github.com/r-lib/actions/tree/master/setup-pandoc
# https://github.com/marketplace/actions/ci-skip-action
on:
  workflow_dispatch
#  push:
#    branches:
#      - main
#      - master

name: pkgdown

jobs:
  pkgdown:
 #   if: "contains(github.event.head_commit.message, '[rebuild site]')"
 #   runs-on: macOS-latest
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      ## attempt to control over-parallelization
      OPENBLAS_NUM_THREADS: 1
      OMP_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - name: extra Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev 
      - name: Install pkg
        run: |
          install.packages("devtools")
          devtools::install()
        shell: Rscript {0}
      - name: Rebuild site
        run: |
          pkgdown::build_site(preview=FALSE)
        shell: Rscript {0}
      - name: Commit site
        run: |
          git config --global user.name 'pkgdown-bot'
          git config --global user.email 'pkgdown-bot@users.noreply.github.com'
          git add --all
          git commit -am "Site rebuild"
          git push
